server:
  port: 18083
#jdbc
spring:
  datasource:
    url: jdbc:mysql://192.168.4.244:3306/demo
    username: root
    password: 123456
  application:
    name: user-service
#mybatis
mybatis:
  type-aliases-package: com.lyp.userservice1.pojo
logging:
  level:
    com.lyp.demo: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18080/eureka,http://127.0.0.1:18081/eureka
  instance:
    lease-expiration-duration-in-seconds: 30 #默认90s
    lease-renewal-interval-in-seconds: 10 #默认30s
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #配置服务的Host为ip
    ip-address: 192.168.11.74 #配置服务的ip（不配置为自动获取）
