server:
  port: 80
#jdbc
spring:
  datasource:
    url: jdbc:mysql://192.168.4.244:3306/demo
    username: root
    password: 123456
#mybatis
mybatis:
  type-aliases-package: com.lyp.userservice.pojo
#日志级别
logging:
  level.com.lyp.demo: debug
