server:
  port: 18084
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18080/eureka,http://127.0.0.1:18081/eureka
  instance:
    lease-expiration-duration-in-seconds: 30 #默认90s
    lease-renewal-interval-in-seconds: 10 #默认30s
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
logging:
  level:
    org.springframework: debug
    com.lyp.consumer: debug
user-service:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  #RoundRobinRule 默认为轮询
    ConnectTimeout: 250 #ribbon的连接超时时间  没效果
    ReadTimeout: 250 #ribbon数据读取时间      没效果
    OkToRetryOnAllOperations: true #是否所有操作都进行重试
    MaxAutoRetriesNextServer: 2 #切换实例的重试次数
    MaxAutoRetries: 1 #对当前实例的重试次数
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #设置hystrix的超时时间(hystrix的超时时间要大于 (1 + MaxAutoRetries + MaxAutoRetriesNextServer) * ReadTimeout 比较好)
